require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    "bash",
    "bibtex",
    "c",
    "cmake",
    "cpp",
    "css",
    "dockerfile",
    "erlang",
    "go",
    "graphql",
    "hjson",
    "html",
    "java",
    "javascript",
    "json",
    "json5",
    "julia",
    "latex",
    "lua",
    "make",
    "markdown",
    "ocaml",
    "pascal",
    "perl",
    "php",
    "prisma",
    "proto",
    "python",
    "regex",
    "ruby",
    "rust",
    "solidity",
    "swift",
    "tsx",
    "typescript",
    "vim",
    "vue",
    "yaml",
  },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
    disable = {"tex", "latex"},
  },
}
-- TODO use treesitter math zone: https://github.com/nvim-treesitter/nvim-treesitter/issues/1184
